import { roboto, robotoBold, robotoLight } from '@/app/fonts/Roboto'
import type { Metadata } from 'next'

import '@/app/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`${roboto} ${robotoBold} ${robotoLight}`}
      >
        {children}
      </body>
    </html>
  )
}
